// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/stratagems/General Stratagems/Super Earth Flag_128.png
const char * ui_img_stratagems_general_stratagems_super_earth_flag_128_png =
    "S:assets/stratagems/General Stratagems/Super Earth Flag_128.png";
