// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/stratagems/Engineering Bay/Anti-Personnel Minefield_64.png
const char * ui_img_1071012764 = "S:assets/stratagems/Engineering Bay/Anti-Personnel Minefield_64.png";
