// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/stratagems/Patriotic Administration Center/Spear_128.png
const char * ui_img_stratagems_patriotic_administration_center_spear_128_png =
    "S:assets/stratagems/Patriotic Administration Center/Spear_128.png";
