// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/stratagems/Orbital Cannons/Orbital 380MM HE Barrage_64.png
const char * ui_img_stratagems_orbital_cannons_orbital_380mm_he_barrage_64_png =
    "S:assets/stratagems/Orbital Cannons/Orbital 380MM HE Barrage_64.png";
