// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/stratagems/Hangar/Eagle Strafing Run_128.png
const char * ui_img_stratagems_hangar_eagle_strafing_run_128_png =
    "S:assets/stratagems/Hangar/Eagle Strafing Run_128.png";
