// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Intro
void ui_Intro_screen_init(void);
void ui_event_Intro(lv_event_t * e);
lv_obj_t * ui_Intro;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES


// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
lv_obj_t * ui_Setup;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Weapons;
lv_obj_t * ui_Container2;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
void ui_event_Button40(lv_event_t * e);
lv_obj_t * ui_Button40;
void ui_event_Button41(lv_event_t * e);
lv_obj_t * ui_Button41;
void ui_event_Button42(lv_event_t * e);
lv_obj_t * ui_Button42;
void ui_event_Button43(lv_event_t * e);
lv_obj_t * ui_Button43;
void ui_event_Button44(lv_event_t * e);
lv_obj_t * ui_Button44;
lv_obj_t * ui_Backpacks;
lv_obj_t * ui_Container1;
void ui_event_Button46(lv_event_t * e);
lv_obj_t * ui_Button46;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
void ui_event_Button45(lv_event_t * e);
lv_obj_t * ui_Button45;
lv_obj_t * ui_Stationary;
lv_obj_t * ui_Container3;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
void ui_event_Button27(lv_event_t * e);
lv_obj_t * ui_Button27;
void ui_event_Button28(lv_event_t * e);
lv_obj_t * ui_Button28;
void ui_event_Button29(lv_event_t * e);
lv_obj_t * ui_Button29;
void ui_event_Button30(lv_event_t * e);
lv_obj_t * ui_Button30;
void ui_event_Button31(lv_event_t * e);
lv_obj_t * ui_Button31;
void ui_event_Button38(lv_event_t * e);
lv_obj_t * ui_Button38;
lv_obj_t * ui_Strikes;
lv_obj_t * ui_Container4;
void ui_event_Button57(lv_event_t * e);
lv_obj_t * ui_Button57;
void ui_event_Button58(lv_event_t * e);
lv_obj_t * ui_Button58;
void ui_event_Button47(lv_event_t * e);
lv_obj_t * ui_Button47;
void ui_event_Button48(lv_event_t * e);
lv_obj_t * ui_Button48;
void ui_event_Button49(lv_event_t * e);
lv_obj_t * ui_Button49;
void ui_event_Button51(lv_event_t * e);
lv_obj_t * ui_Button51;
void ui_event_Button50(lv_event_t * e);
lv_obj_t * ui_Button50;
void ui_event_Button52(lv_event_t * e);
lv_obj_t * ui_Button52;
void ui_event_Button53(lv_event_t * e);
lv_obj_t * ui_Button53;
void ui_event_Button54(lv_event_t * e);
lv_obj_t * ui_Button54;
void ui_event_Button55(lv_event_t * e);
lv_obj_t * ui_Button55;
void ui_event_Button56(lv_event_t * e);
lv_obj_t * ui_Button56;
lv_obj_t * ui_Eagle;
lv_obj_t * ui_Container7;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
void ui_event_Button34(lv_event_t * e);
lv_obj_t * ui_Button34;
void ui_event_Button35(lv_event_t * e);
lv_obj_t * ui_Button35;
void ui_event_Button36(lv_event_t * e);
lv_obj_t * ui_Button36;
void ui_event_Button37(lv_event_t * e);
lv_obj_t * ui_Button37;
lv_obj_t * ui_Amount;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
void ui_event_Button69(lv_event_t * e);
lv_obj_t * ui_Button69;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
lv_obj_t * uic_Amount;


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t * ui_Game;
lv_obj_t * ui_Container6;
void ui_event_Button68(lv_event_t * e);
lv_obj_t * ui_Button68;
void ui_event_Button59(lv_event_t * e);
lv_obj_t * ui_Button59;
void ui_event_Button60(lv_event_t * e);
lv_obj_t * ui_Button60;
void ui_event_Button61(lv_event_t * e);
lv_obj_t * ui_Button61;
void ui_event_CustomStratagem1(lv_event_t * e);
lv_obj_t * ui_CustomStratagem1;
void ui_event_CustomStratagem2(lv_event_t * e);
lv_obj_t * ui_CustomStratagem2;
void ui_event_CustomStratagem3(lv_event_t * e);
lv_obj_t * ui_CustomStratagem3;
void ui_event_CustomStratagem4(lv_event_t * e);
lv_obj_t * ui_CustomStratagem4;
void ui_event_Button39(lv_event_t * e);
lv_obj_t * ui_Button39;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[4] = {&ui_img_sg_1201_png, &ui_img_sg_1202_png, &ui_img_sg_3801_png, &ui_img_sg_3802_png};
const lv_img_dsc_t * ui_imgset_ac[2] = {&ui_img_sg_ac1_png, &ui_img_sg_ac2_png};
const lv_img_dsc_t * ui_imgset_acs[2] = {&ui_img_sg_acs1_png, &ui_img_sg_acs2_png};
const lv_img_dsc_t * ui_imgset_amr[2] = {&ui_img_sg_amr1_png, &ui_img_sg_amr2_png};
const lv_img_dsc_t * ui_imgset_apm[2] = {&ui_img_sg_apm1_png, &ui_img_sg_apm2_png};
const lv_img_dsc_t * ui_imgset_arl[2] = {&ui_img_sg_arl1_png, &ui_img_sg_arl2_png};
const lv_img_dsc_t * ui_imgset_at[2] = {&ui_img_sg_at1_png, &ui_img_sg_at2_png};
const lv_img_dsc_t * ui_imgset_atm[2] = {&ui_img_sg_atm1_png, &ui_img_sg_atm2_png};
const lv_img_dsc_t * ui_imgset_bsb[2] = {&ui_img_sg_bsb1_png, &ui_img_sg_bsb2_png};
const lv_img_dsc_t * ui_imgset_c[2] = {&ui_img_sg_c1_png, &ui_img_sg_c2_png};
const lv_img_dsc_t * ui_imgset_dfv[2] = {&ui_img_sg_dfv1_png, &ui_img_sg_dfv2_png};
const lv_img_dsc_t * ui_imgset_e[4] = {&ui_img_sg_e1101_png, &ui_img_sg_e1102_png, &ui_img_sg_e5001_png, &ui_img_sg_e5002_png};
const lv_img_dsc_t * ui_imgset_ea[2] = {&ui_img_sg_ea1_png, &ui_img_sg_ea2_png};
const lv_img_dsc_t * ui_imgset_eat[2] = {&ui_img_sg_eat1_png, &ui_img_sg_eat2_png};
const lv_img_dsc_t * ui_imgset_ecb[2] = {&ui_img_sg_ecb1_png, &ui_img_sg_ecb2_png};
const lv_img_dsc_t * ui_imgset_ee[2] = {&ui_img_sg_ee1_png, &ui_img_sg_ee2_png};
const lv_img_dsc_t * ui_imgset_ems[2] = {&ui_img_sg_ems1_png, &ui_img_sg_ems2_png};
const lv_img_dsc_t * ui_imgset_ena[2] = {&ui_img_sg_ena1_png, &ui_img_sg_ena2_png};
const lv_img_dsc_t * ui_imgset_er[2] = {&ui_img_sg_er1_png, &ui_img_sg_er2_png};
const lv_img_dsc_t * ui_imgset_esr[2] = {&ui_img_sg_esr1_png, &ui_img_sg_esr2_png};
const lv_img_dsc_t * ui_imgset_ess[2] = {&ui_img_sg_ess1_png, &ui_img_sg_ess2_png};
const lv_img_dsc_t * ui_imgset_ft[2] = {&ui_img_sg_ft1_png, &ui_img_sg_ft2_png};
const lv_img_dsc_t * ui_imgset_gd[2] = {&ui_img_sg_gd1_png, &ui_img_sg_gd2_png};
const lv_img_dsc_t * ui_imgset_gdb[2] = {&ui_img_sg_gdb1_png, &ui_img_sg_gdb2_png};
const lv_img_dsc_t * ui_imgset_gdr[2] = {&ui_img_sg_gdr1_png, &ui_img_sg_gdr2_png};
const lv_img_dsc_t * ui_imgset_gl[2] = {&ui_img_sg_gl1_png, &ui_img_sg_gl2_png};
const lv_img_dsc_t * ui_imgset_gs[2] = {&ui_img_sg_gs1_png, &ui_img_sg_gs2_png};
const lv_img_dsc_t * ui_imgset_hb[2] = {&ui_img_sg_hb1_png, &ui_img_sg_hb2_png};
const lv_img_dsc_t * ui_imgset_hbd[2] = {&ui_img_sg_hbd1_png, &ui_img_sg_hbd2_png};
const lv_img_dsc_t * ui_imgset_hmg[2] = {&ui_img_sg_hmg1_png, &ui_img_sg_hmg2_png};
const lv_img_dsc_t * ui_imgset_hmge[2] = {&ui_img_sg_hmge1_png, &ui_img_sg_hmge2_png};
const lv_img_dsc_t * ui_imgset_im[2] = {&ui_img_sg_im1_png, &ui_img_sg_im2_png};
const lv_img_dsc_t * ui_imgset_jp[2] = {&ui_img_sg_jp1_png, &ui_img_sg_jp2_png};
const lv_img_dsc_t * ui_imgset_lc[2] = {&ui_img_sg_lc1_png, &ui_img_sg_lc2_png};
const lv_img_dsc_t * ui_imgset_mg[2] = {&ui_img_sg_mg1_png, &ui_img_sg_mg2_png};
const lv_img_dsc_t * ui_imgset_mgs[2] = {&ui_img_sg_mgs1_png, &ui_img_sg_mgs2_png};
const lv_img_dsc_t * ui_imgset_ms[2] = {&ui_img_sg_ms1_png, &ui_img_sg_ms2_png};
const lv_img_dsc_t * ui_imgset_oas[2] = {&ui_img_sg_oas1_png, &ui_img_sg_oas2_png};
const lv_img_dsc_t * ui_imgset_oes[2] = {&ui_img_sg_oes1_png, &ui_img_sg_oes2_png};
const lv_img_dsc_t * ui_imgset_ogb[2] = {&ui_img_sg_ogb1_png, &ui_img_sg_ogb2_png};
const lv_img_dsc_t * ui_imgset_ogs[2] = {&ui_img_sg_ogs1_png, &ui_img_sg_ogs2_png};
const lv_img_dsc_t * ui_imgset_oif[2] = {&ui_img_sg_oif1_png, &ui_img_sg_oif2_png};
const lv_img_dsc_t * ui_imgset_ol[2] = {&ui_img_sg_ol1_png, &ui_img_sg_ol2_png};
const lv_img_dsc_t * ui_imgset_onb[2] = {&ui_img_sg_onb1_png, &ui_img_sg_onb2_png};
const lv_img_dsc_t * ui_imgset_ops[2] = {&ui_img_sg_ops1_png, &ui_img_sg_ops2_png};
const lv_img_dsc_t * ui_imgset_ors[2] = {&ui_img_sg_ors1_png, &ui_img_sg_ors2_png};
const lv_img_dsc_t * ui_imgset_oss[2] = {&ui_img_sg_oss1_png, &ui_img_sg_oss2_png};
const lv_img_dsc_t * ui_imgset_owb[2] = {&ui_img_sg_owb1_png, &ui_img_sg_owb2_png};
const lv_img_dsc_t * ui_imgset_pd[2] = {&ui_img_sg_pd1_png, &ui_img_sg_pd2_png};
const lv_img_dsc_t * ui_imgset_pe[2] = {&ui_img_sg_pe1_png, &ui_img_sg_pe2_png};
const lv_img_dsc_t * ui_imgset_qc[2] = {&ui_img_sg_qc1_png, &ui_img_sg_qc2_png};
const lv_img_dsc_t * ui_imgset_res[2] = {&ui_img_sg_res1_png, &ui_img_sg_res2_png};
const lv_img_dsc_t * ui_imgset_rf[2] = {&ui_img_sg_rf1_png, &ui_img_sg_rf2_png};
const lv_img_dsc_t * ui_imgset_rg[2] = {&ui_img_sg_rg1_png, &ui_img_sg_rg2_png};
const lv_img_dsc_t * ui_imgset_rr[2] = {&ui_img_sg_rr1_png, &ui_img_sg_rr2_png};
const lv_img_dsc_t * ui_imgset_rs[2] = {&ui_img_sg_rs1_png, &ui_img_sg_rs2_png};
const lv_img_dsc_t * ui_imgset_seaf[2] = {&ui_img_sg_seaf1_png, &ui_img_sg_seaf2_png};
const lv_img_dsc_t * ui_imgset_sef[2] = {&ui_img_sg_sef1_png, &ui_img_sg_sef2_png};
const lv_img_dsc_t * ui_imgset_sgp[2] = {&ui_img_sg_sgp1_png, &ui_img_sg_sgp2_png};
const lv_img_dsc_t * ui_imgset_sgr[2] = {&ui_img_sg_sgr1_png, &ui_img_sg_sgr2_png};
const lv_img_dsc_t * ui_imgset_sos[2] = {&ui_img_sg_sos1_png, &ui_img_sg_sos2_png};
const lv_img_dsc_t * ui_imgset_sp[2] = {&ui_img_sg_sp1_png, &ui_img_sg_sp2_png};
const lv_img_dsc_t * ui_imgset_spr[2] = {&ui_img_sg_spr1_png, &ui_img_sg_spr2_png};
const lv_img_dsc_t * ui_imgset_ste[2] = {&ui_img_sg_ste1_png, &ui_img_sg_ste2_png};
const lv_img_dsc_t * ui_imgset_sup[2] = {&ui_img_sg_sup1_png, &ui_img_sg_sup2_png};
const lv_img_dsc_t * ui_imgset_sw[2] = {&ui_img_sg_sw1_png, &ui_img_sg_sw2_png};
const lv_img_dsc_t * ui_imgset_td[2] = {&ui_img_sg_td1_png, &ui_img_sg_td2_png};
const lv_img_dsc_t * ui_imgset_tt[2] = {&ui_img_sg_tt1_png, &ui_img_sg_tt2_png};
const lv_img_dsc_t * ui_imgset_ud[2] = {&ui_img_sg_ud1_png, &ui_img_sg_ud2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Intro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 1000, 2000, &ui_Setup_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button43(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button44(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button46(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button45(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button38(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button57(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button58(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button47(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button48(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button49(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button51(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button50(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button52(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button53(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button54(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button55(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button56(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button37(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button69(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetStratagems(e);
    }
}

void ui_event_Button68(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem1(e);
    }
}

void ui_event_Button59(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem2(e);
    }
}

void ui_event_Button60(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem3(e);
    }
}

void ui_event_Button61(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem4(e);
    }
}

void ui_event_CustomStratagem1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem5(e);
    }
}

void ui_event_CustomStratagem2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem6(e);
    }
}

void ui_event_CustomStratagem3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem7(e);
    }
}

void ui_event_CustomStratagem4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem8(e);
    }
}

void ui_event_Button39(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 0, &ui_Setup_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Intro_screen_init();
    ui_Setup_screen_init();
    ui_Game_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Intro);
}
