// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Reinforce_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Intro
void ui_Intro_screen_init(void);
void ui_event_Intro(lv_event_t * e);
lv_obj_t * ui_Intro;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES


// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
lv_obj_t * ui_Setup;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Mission;
lv_obj_t * ui_Container1;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Weapons;
lv_obj_t * ui_Container2;
void ui_event_Button62(lv_event_t * e);
lv_obj_t * ui_Button62;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Eagle;
lv_obj_t * ui_Button24;
lv_obj_t * ui_Button25;
lv_obj_t * ui_Button26;
lv_obj_t * ui_Button27;
lv_obj_t * ui_Button28;
lv_obj_t * ui_Button29;
lv_obj_t * ui_Button30;
lv_obj_t * ui_Button31;
lv_obj_t * ui_Strikes;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button32;
lv_obj_t * ui_Button33;
lv_obj_t * ui_Button34;
lv_obj_t * ui_Button35;
lv_obj_t * ui_Button36;
lv_obj_t * ui_Button37;
lv_obj_t * ui_Button38;
lv_obj_t * ui_Button40;
lv_obj_t * ui_Button41;
lv_obj_t * ui_Button42;
lv_obj_t * ui_Defensive;
lv_obj_t * ui_Button39;
lv_obj_t * ui_Button43;
lv_obj_t * ui_Button44;
lv_obj_t * ui_Button45;
lv_obj_t * ui_Button46;
lv_obj_t * ui_Button47;
lv_obj_t * ui_Button48;
lv_obj_t * ui_Button49;
lv_obj_t * ui_Button50;
lv_obj_t * ui_Button51;
lv_obj_t * ui_Button52;
lv_obj_t * ui_Backpacks;
lv_obj_t * ui_Button53;
lv_obj_t * ui_Button54;
lv_obj_t * ui_Button55;
lv_obj_t * ui_Button56;
lv_obj_t * ui_Button57;
lv_obj_t * ui_Button58;
lv_obj_t * ui_Vehicles;
lv_obj_t * ui_Button59;
lv_obj_t * ui_Button60;
lv_obj_t * ui_Button61;
lv_obj_t * ui_Amount;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
lv_obj_t * uic_Amount;


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t * ui_Game;
void ui_event_Button64(lv_event_t * e);
lv_obj_t * ui_Button64;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Button65;
lv_obj_t * ui_Button66;
lv_obj_t * ui_Button67;
lv_obj_t * ui_Button68;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Button69;
lv_obj_t * ui_Button70;
lv_obj_t * ui_Button71;
lv_obj_t * ui_Button72;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const char * ui_imgset_frame_[42] = {"S:assets/reinforce/frame_00.png", "S:assets/reinforce/frame_01.png", "S:assets/reinforce/frame_02.png", "S:assets/reinforce/frame_03.png", "S:assets/reinforce/frame_04.png", "S:assets/reinforce/frame_05.png", "S:assets/reinforce/frame_06.png", "S:assets/reinforce/frame_07.png", "S:assets/reinforce/frame_08.png", "S:assets/reinforce/frame_09.png", "S:assets/reinforce/frame_10.png", "S:assets/reinforce/frame_11.png", "S:assets/reinforce/frame_12.png", "S:assets/reinforce/frame_13.png", "S:assets/reinforce/frame_14.png", "S:assets/reinforce/frame_15.png", "S:assets/reinforce/frame_16.png", "S:assets/reinforce/frame_17.png", "S:assets/reinforce/frame_18.png", "S:assets/reinforce/frame_19.png", "S:assets/reinforce/frame_20.png", "S:assets/reinforce/frame_21.png", "S:assets/reinforce/frame_22.png", "S:assets/reinforce/frame_23.png", "S:assets/reinforce/frame_24.png", "S:assets/reinforce/frame_25.png", "S:assets/reinforce/frame_26.png", "S:assets/reinforce/frame_27.png", "S:assets/reinforce/frame_28.png", "S:assets/reinforce/frame_29.png", "S:assets/reinforce/frame_30.png", "S:assets/reinforce/frame_31.png", "S:assets/reinforce/frame_32.png", "S:assets/reinforce/frame_33.png", "S:assets/reinforce/frame_34.png", "S:assets/reinforce/frame_35.png", "S:assets/reinforce/frame_36.png", "S:assets/reinforce/frame_37.png", "S:assets/reinforce/frame_38.png", "S:assets/reinforce/frame_39.png", "S:assets/reinforce/frame_40.png", "S:assets/reinforce/frame_41.png"};
const char * ui_imgset_000_helldivers[1] = {"S:assets/stratagems/000_helldivers2.png"};
const char * ui_imgset_class_[7] = {"S:assets/stratagems/CLASS_1.png", "S:assets/stratagems/CLASS_2.png", "S:assets/stratagems/CLASS_3.png", "S:assets/stratagems/CLASS_4.png", "S:assets/stratagems/CLASS_5.png", "S:assets/stratagems/CLASS_6.png", "S:assets/stratagems/CLASS_7.png"};
const char * ui_imgset_defensive_[11] = {"S:assets/stratagems/DEFENSIVE_1.png", "S:assets/stratagems/DEFENSIVE_10.png", "S:assets/stratagems/DEFENSIVE_11.png", "S:assets/stratagems/DEFENSIVE_2.png", "S:assets/stratagems/DEFENSIVE_3.png", "S:assets/stratagems/DEFENSIVE_4.png", "S:assets/stratagems/DEFENSIVE_5.png", "S:assets/stratagems/DEFENSIVE_6.png", "S:assets/stratagems/DEFENSIVE_7.png", "S:assets/stratagems/DEFENSIVE_8.png", "S:assets/stratagems/DEFENSIVE_9.png"};
const char * ui_imgset_offensive_[18] = {"S:assets/stratagems/OFFENSIVE_1.png", "S:assets/stratagems/OFFENSIVE_10.png", "S:assets/stratagems/OFFENSIVE_11.png", "S:assets/stratagems/OFFENSIVE_12.png", "S:assets/stratagems/OFFENSIVE_2.png", "S:assets/stratagems/OFFENSIVE_13.png", "S:assets/stratagems/OFFENSIVE_3.png", "S:assets/stratagems/OFFENSIVE_14.png", "S:assets/stratagems/OFFENSIVE_4.png", "S:assets/stratagems/OFFENSIVE_15.png", "S:assets/stratagems/OFFENSIVE_5.png", "S:assets/stratagems/OFFENSIVE_16.png", "S:assets/stratagems/OFFENSIVE_6.png", "S:assets/stratagems/OFFENSIVE_17.png", "S:assets/stratagems/OFFENSIVE_7.png", "S:assets/stratagems/OFFENSIVE_18.png", "S:assets/stratagems/OFFENSIVE_8.png", "S:assets/stratagems/OFFENSIVE_9.png"};
const char * ui_imgset_supply_[19] = {"S:assets/stratagems/SUPPLY_1.png", "S:assets/stratagems/SUPPLY_10.png", "S:assets/stratagems/SUPPLY_11.png", "S:assets/stratagems/SUPPLY_12.png", "S:assets/stratagems/SUPPLY_2.png", "S:assets/stratagems/SUPPLY_13.png", "S:assets/stratagems/SUPPLY_3.png", "S:assets/stratagems/SUPPLY_14.png", "S:assets/stratagems/SUPPLY_4.png", "S:assets/stratagems/SUPPLY_15.png", "S:assets/stratagems/SUPPLY_5.png", "S:assets/stratagems/SUPPLY_16.png", "S:assets/stratagems/SUPPLY_6.png", "S:assets/stratagems/SUPPLY_17.png", "S:assets/stratagems/SUPPLY_7.png", "S:assets/stratagems/SUPPLY_18.png", "S:assets/stratagems/SUPPLY_8.png", "S:assets/stratagems/SUPPLY_19.png", "S:assets/stratagems/SUPPLY_9.png"};
const char * ui_imgset_support_[10] = {"S:assets/stratagems/SUPPORT_1.png", "S:assets/stratagems/SUPPORT_10.png", "S:assets/stratagems/SUPPORT_2.png", "S:assets/stratagems/SUPPORT_3.png", "S:assets/stratagems/SUPPORT_4.png", "S:assets/stratagems/SUPPORT_5.png", "S:assets/stratagems/SUPPORT_6.png", "S:assets/stratagems/SUPPORT_7.png", "S:assets/stratagems/SUPPORT_8.png", "S:assets/stratagems/SUPPORT_9.png"};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Reinforce_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_frame_;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_frame_) / (sizeof(lv_img_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 4100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 41);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Intro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 1000, 2000, &ui_Setup_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Button62(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_bar_increment(ui_Amount, -1, LV_ANIM_ON);
    }
}

void ui_event_Button64(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetStratagems(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Intro_screen_init();
    ui_Setup_screen_init();
    ui_Game_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Intro);
}
