// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SplashFade_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Intro
void ui_Intro_screen_init(void);
void ui_event_Intro(lv_event_t * e);
lv_obj_t * ui_Intro;
lv_obj_t * ui_Splash;
// CUSTOM VARIABLES


// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
void ui_event_Setup(lv_event_t * e);
lv_obj_t * ui_Setup;
lv_obj_t * ui_TabStratagems;
lv_obj_t * ui_Weapon;
lv_obj_t * ui_Container2;
void ui_event_WeaponsMG(lv_event_t * e);
lv_obj_t * ui_WeaponsMG;
void ui_event_WeaponsHMG(lv_event_t * e);
lv_obj_t * ui_WeaponsHMG;
void ui_event_WeaponsSW(lv_event_t * e);
lv_obj_t * ui_WeaponsSW;
void ui_event_WeaponsAC(lv_event_t * e);
lv_obj_t * ui_WeaponsAC;
void ui_event_WeaponsAMR(lv_event_t * e);
lv_obj_t * ui_WeaponsAMR;
void ui_event_WeaponsARL(lv_event_t * e);
lv_obj_t * ui_WeaponsARL;
void ui_event_WeaponsC(lv_event_t * e);
lv_obj_t * ui_WeaponsC;
void ui_event_WeaponsEAT(lv_event_t * e);
lv_obj_t * ui_WeaponsEAT;
void ui_event_WeaponsGL(lv_event_t * e);
lv_obj_t * ui_WeaponsGL;
void ui_event_WeaponsRG(lv_event_t * e);
lv_obj_t * ui_WeaponsRG;
void ui_event_WeaponsRR(lv_event_t * e);
lv_obj_t * ui_WeaponsRR;
void ui_event_WeaponsSPR(lv_event_t * e);
lv_obj_t * ui_WeaponsSPR;
void ui_event_WeaponsQC(lv_event_t * e);
lv_obj_t * ui_WeaponsQC;
void ui_event_WeaponsLC(lv_event_t * e);
lv_obj_t * ui_WeaponsLC;
void ui_event_WeaponsAT(lv_event_t * e);
lv_obj_t * ui_WeaponsAT;
void ui_event_WeaponsFT(lv_event_t * e);
lv_obj_t * ui_WeaponsFT;
void ui_event_WeaponsSTE(lv_event_t * e);
lv_obj_t * ui_WeaponsSTE;
lv_obj_t * ui_Backpack;
lv_obj_t * ui_Container1;
void ui_event_BackpacksBSB(lv_event_t * e);
lv_obj_t * ui_BackpacksBSB;
void ui_event_BackpacksSGP(lv_event_t * e);
lv_obj_t * ui_BackpacksSGP;
void ui_event_BackpacksGD(lv_event_t * e);
lv_obj_t * ui_BackpacksGD;
void ui_event_BackpacksGDB(lv_event_t * e);
lv_obj_t * ui_BackpacksGDB;
void ui_event_BackpacksGDR(lv_event_t * e);
lv_obj_t * ui_BackpacksGDR;
void ui_event_BackpacksSUP(lv_event_t * e);
lv_obj_t * ui_BackpacksSUP;
void ui_event_BackpacksJP(lv_event_t * e);
lv_obj_t * ui_BackpacksJP;
void ui_event_BackpacksPE(lv_event_t * e);
lv_obj_t * ui_BackpacksPE;
void ui_event_BackpacksEE(lv_event_t * e);
lv_obj_t * ui_BackpacksEE;
lv_obj_t * ui_Stationary;
lv_obj_t * ui_Container3;
void ui_event_StationaryMGS(lv_event_t * e);
lv_obj_t * ui_StationaryMGS;
void ui_event_StationaryGS(lv_event_t * e);
lv_obj_t * ui_StationaryGS;
void ui_event_StationaryACS(lv_event_t * e);
lv_obj_t * ui_StationaryACS;
void ui_event_StationaryHMGE(lv_event_t * e);
lv_obj_t * ui_StationaryHMGE;
void ui_event_StationaryTT(lv_event_t * e);
lv_obj_t * ui_StationaryTT;
void ui_event_StationarySGR(lv_event_t * e);
lv_obj_t * ui_StationarySGR;
void ui_event_StationaryMS(lv_event_t * e);
lv_obj_t * ui_StationaryMS;
void ui_event_StationaryRS(lv_event_t * e);
lv_obj_t * ui_StationaryRS;
void ui_event_StationaryEMS(lv_event_t * e);
lv_obj_t * ui_StationaryEMS;
void ui_event_StationaryAPM(lv_event_t * e);
lv_obj_t * ui_StationaryAPM;
void ui_event_StationaryATM(lv_event_t * e);
lv_obj_t * ui_StationaryATM;
void ui_event_StationaryIM(lv_event_t * e);
lv_obj_t * ui_StationaryIM;
lv_obj_t * ui_Strike;
lv_obj_t * ui_Container4;
void ui_event_Strikes120(lv_event_t * e);
lv_obj_t * ui_Strikes120;
void ui_event_Strikes380(lv_event_t * e);
lv_obj_t * ui_Strikes380;
void ui_event_StrikesORS(lv_event_t * e);
lv_obj_t * ui_StrikesORS;
void ui_event_StrikesOGB(lv_event_t * e);
lv_obj_t * ui_StrikesOGB;
void ui_event_StrikesOAS(lv_event_t * e);
lv_obj_t * ui_StrikesOAS;
void ui_event_StrikesOL(lv_event_t * e);
lv_obj_t * ui_StrikesOL;
void ui_event_StrikesOPS(lv_event_t * e);
lv_obj_t * ui_StrikesOPS;
void ui_event_StrikesOWB(lv_event_t * e);
lv_obj_t * ui_StrikesOWB;
void ui_event_StrikesOES(lv_event_t * e);
lv_obj_t * ui_StrikesOES;
void ui_event_StrikesONB(lv_event_t * e);
lv_obj_t * ui_StrikesONB;
void ui_event_StrikesOGS(lv_event_t * e);
lv_obj_t * ui_StrikesOGS;
void ui_event_StrikesOSS(lv_event_t * e);
lv_obj_t * ui_StrikesOSS;
lv_obj_t * ui_Eagle;
lv_obj_t * ui_Container7;
void ui_event_Eagle110(lv_event_t * e);
lv_obj_t * ui_Eagle110;
void ui_event_Eagle500(lv_event_t * e);
lv_obj_t * ui_Eagle500;
void ui_event_EagleA(lv_event_t * e);
lv_obj_t * ui_EagleA;
void ui_event_EagleCB(lv_event_t * e);
lv_obj_t * ui_EagleCB;
void ui_event_EagleSR(lv_event_t * e);
lv_obj_t * ui_EagleSR;
void ui_event_EagleNA(lv_event_t * e);
lv_obj_t * ui_EagleNA;
void ui_event_EagleSS(lv_event_t * e);
lv_obj_t * ui_EagleSS;
lv_obj_t * ui_SetupFooter;
void ui_event_BtnConfig(lv_event_t * e);
lv_obj_t * ui_BtnConfig;
lv_obj_t * ui_LblConfig;
void ui_event_BtnReset(lv_event_t * e);
lv_obj_t * ui_BtnReset;
lv_obj_t * ui_LblReset;
lv_obj_t * ui_BarAmount;
lv_obj_t * ui_Container5;
lv_obj_t * ui_LblCurAmount;
lv_obj_t * ui_LblMaxAmount;
void ui_event_BtnPlay(lv_event_t * e);
lv_obj_t * ui_BtnPlay;
lv_obj_t * ui_LblPlay;
// CUSTOM VARIABLES
lv_obj_t * uic_BarAmount;
lv_obj_t * uic_LabelAmount;


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t * ui_Game;
lv_obj_t * ui_BoxStratagems;
void ui_event_BtnReinforce(lv_event_t * e);
lv_obj_t * ui_BtnReinforce;
void ui_event_BtnResupply(lv_event_t * e);
lv_obj_t * ui_BtnResupply;
void ui_event_BtnSOS(lv_event_t * e);
lv_obj_t * ui_BtnSOS;
void ui_event_BtnRearm(lv_event_t * e);
lv_obj_t * ui_BtnRearm;
void ui_event_CustomStratagem1(lv_event_t * e);
lv_obj_t * ui_CustomStratagem1;
void ui_event_CustomStratagem2(lv_event_t * e);
lv_obj_t * ui_CustomStratagem2;
void ui_event_CustomStratagem3(lv_event_t * e);
lv_obj_t * ui_CustomStratagem3;
void ui_event_CustomStratagem4(lv_event_t * e);
lv_obj_t * ui_CustomStratagem4;
lv_obj_t * ui_GameFooter;
void ui_event_BtnBack(lv_event_t * e);
lv_obj_t * ui_BtnBack;
lv_obj_t * ui_LblBack;
// CUSTOM VARIABLES


// SCREEN: ui_Config
void ui_Config_screen_init(void);
lv_obj_t * ui_Config;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Display;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label2;
lv_obj_t * ui_LblBrightness;
lv_obj_t * ui_LblBrightness1;
void ui_event_SldBrightness(lv_event_t * e);
lv_obj_t * ui_SldBrightness;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Label5;
void ui_event_ChbFlip(lv_event_t * e);
lv_obj_t * ui_ChbFlip;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Audio;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label1;
void ui_event_ChbMute(lv_event_t * e);
lv_obj_t * ui_ChbMute;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Input;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label3;
lv_obj_t * ui_LblDelay;
lv_obj_t * ui_LblDelay1;
void ui_event_SldDelay(lv_event_t * e);
lv_obj_t * ui_SldDelay;
lv_obj_t * ui_Container6;
void ui_event_BtnTest(lv_event_t * e);
lv_obj_t * ui_BtnTest;
lv_obj_t * ui_LblTest;
lv_obj_t * ui_Label16;
void ui_event_SetupFooter2(lv_event_t * e);
lv_obj_t * ui_SetupFooter2;
void ui_event_BtnSetup(lv_event_t * e);
lv_obj_t * ui_BtnSetup;
lv_obj_t * ui_LblSetup;
lv_obj_t * ui_Container11;
void ui_event_BtnDefault(lv_event_t * e);
lv_obj_t * ui_BtnDefault;
lv_obj_t * ui_LblDefault;
void ui_event_BtnReboot(lv_event_t * e);
lv_obj_t * ui_BtnReboot;
lv_obj_t * ui_LblReboot;
// CUSTOM VARIABLES
lv_obj_t * uic_ChbFlip;
lv_obj_t * uic_ChbMute;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[4] = {&ui_img_sg_1201_png, &ui_img_sg_1202_png, &ui_img_sg_3801_png, &ui_img_sg_3802_png};
const lv_img_dsc_t * ui_imgset_ac[2] = {&ui_img_sg_ac1_png, &ui_img_sg_ac2_png};
const lv_img_dsc_t * ui_imgset_acs[2] = {&ui_img_sg_acs1_png, &ui_img_sg_acs2_png};
const lv_img_dsc_t * ui_imgset_amr[2] = {&ui_img_sg_amr1_png, &ui_img_sg_amr2_png};
const lv_img_dsc_t * ui_imgset_apm[2] = {&ui_img_sg_apm1_png, &ui_img_sg_apm2_png};
const lv_img_dsc_t * ui_imgset_arl[2] = {&ui_img_sg_arl1_png, &ui_img_sg_arl2_png};
const lv_img_dsc_t * ui_imgset_at[2] = {&ui_img_sg_at1_png, &ui_img_sg_at2_png};
const lv_img_dsc_t * ui_imgset_atm[2] = {&ui_img_sg_atm1_png, &ui_img_sg_atm2_png};
const lv_img_dsc_t * ui_imgset_bsb[2] = {&ui_img_sg_bsb1_png, &ui_img_sg_bsb2_png};
const lv_img_dsc_t * ui_imgset_c[2] = {&ui_img_sg_c1_png, &ui_img_sg_c2_png};
const lv_img_dsc_t * ui_imgset_dfv[2] = {&ui_img_sg_dfv1_png, &ui_img_sg_dfv2_png};
const lv_img_dsc_t * ui_imgset_e[4] = {&ui_img_sg_e1101_png, &ui_img_sg_e1102_png, &ui_img_sg_e5001_png, &ui_img_sg_e5002_png};
const lv_img_dsc_t * ui_imgset_ea[2] = {&ui_img_sg_ea1_png, &ui_img_sg_ea2_png};
const lv_img_dsc_t * ui_imgset_eat[2] = {&ui_img_sg_eat1_png, &ui_img_sg_eat2_png};
const lv_img_dsc_t * ui_imgset_ecb[2] = {&ui_img_sg_ecb1_png, &ui_img_sg_ecb2_png};
const lv_img_dsc_t * ui_imgset_ee[2] = {&ui_img_sg_ee1_png, &ui_img_sg_ee2_png};
const lv_img_dsc_t * ui_imgset_ems[2] = {&ui_img_sg_ems1_png, &ui_img_sg_ems2_png};
const lv_img_dsc_t * ui_imgset_ena[2] = {&ui_img_sg_ena1_png, &ui_img_sg_ena2_png};
const lv_img_dsc_t * ui_imgset_er[2] = {&ui_img_sg_er1_png, &ui_img_sg_er2_png};
const lv_img_dsc_t * ui_imgset_esr[2] = {&ui_img_sg_esr1_png, &ui_img_sg_esr2_png};
const lv_img_dsc_t * ui_imgset_ess[2] = {&ui_img_sg_ess1_png, &ui_img_sg_ess2_png};
const lv_img_dsc_t * ui_imgset_ft[2] = {&ui_img_sg_ft1_png, &ui_img_sg_ft2_png};
const lv_img_dsc_t * ui_imgset_gd[2] = {&ui_img_sg_gd1_png, &ui_img_sg_gd2_png};
const lv_img_dsc_t * ui_imgset_gdb[2] = {&ui_img_sg_gdb1_png, &ui_img_sg_gdb2_png};
const lv_img_dsc_t * ui_imgset_gdr[2] = {&ui_img_sg_gdr1_png, &ui_img_sg_gdr2_png};
const lv_img_dsc_t * ui_imgset_gl[2] = {&ui_img_sg_gl1_png, &ui_img_sg_gl2_png};
const lv_img_dsc_t * ui_imgset_gs[2] = {&ui_img_sg_gs1_png, &ui_img_sg_gs2_png};
const lv_img_dsc_t * ui_imgset_hb[2] = {&ui_img_sg_hb1_png, &ui_img_sg_hb2_png};
const lv_img_dsc_t * ui_imgset_hbd[2] = {&ui_img_sg_hbd1_png, &ui_img_sg_hbd2_png};
const lv_img_dsc_t * ui_imgset_hmg[2] = {&ui_img_sg_hmg1_png, &ui_img_sg_hmg2_png};
const lv_img_dsc_t * ui_imgset_hmge[2] = {&ui_img_sg_hmge1_png, &ui_img_sg_hmge2_png};
const lv_img_dsc_t * ui_imgset_im[2] = {&ui_img_sg_im1_png, &ui_img_sg_im2_png};
const lv_img_dsc_t * ui_imgset_jp[2] = {&ui_img_sg_jp1_png, &ui_img_sg_jp2_png};
const lv_img_dsc_t * ui_imgset_lc[2] = {&ui_img_sg_lc1_png, &ui_img_sg_lc2_png};
const lv_img_dsc_t * ui_imgset_mg[2] = {&ui_img_sg_mg1_png, &ui_img_sg_mg2_png};
const lv_img_dsc_t * ui_imgset_mgs[2] = {&ui_img_sg_mgs1_png, &ui_img_sg_mgs2_png};
const lv_img_dsc_t * ui_imgset_ms[2] = {&ui_img_sg_ms1_png, &ui_img_sg_ms2_png};
const lv_img_dsc_t * ui_imgset_oas[2] = {&ui_img_sg_oas1_png, &ui_img_sg_oas2_png};
const lv_img_dsc_t * ui_imgset_oes[2] = {&ui_img_sg_oes1_png, &ui_img_sg_oes2_png};
const lv_img_dsc_t * ui_imgset_ogb[2] = {&ui_img_sg_ogb1_png, &ui_img_sg_ogb2_png};
const lv_img_dsc_t * ui_imgset_ogs[2] = {&ui_img_sg_ogs1_png, &ui_img_sg_ogs2_png};
const lv_img_dsc_t * ui_imgset_oif[2] = {&ui_img_sg_oif1_png, &ui_img_sg_oif2_png};
const lv_img_dsc_t * ui_imgset_ol[2] = {&ui_img_sg_ol1_png, &ui_img_sg_ol2_png};
const lv_img_dsc_t * ui_imgset_onb[2] = {&ui_img_sg_onb1_png, &ui_img_sg_onb2_png};
const lv_img_dsc_t * ui_imgset_ops[2] = {&ui_img_sg_ops1_png, &ui_img_sg_ops2_png};
const lv_img_dsc_t * ui_imgset_ors[2] = {&ui_img_sg_ors1_png, &ui_img_sg_ors2_png};
const lv_img_dsc_t * ui_imgset_oss[2] = {&ui_img_sg_oss1_png, &ui_img_sg_oss2_png};
const lv_img_dsc_t * ui_imgset_owb[2] = {&ui_img_sg_owb1_png, &ui_img_sg_owb2_png};
const lv_img_dsc_t * ui_imgset_pd[2] = {&ui_img_sg_pd1_png, &ui_img_sg_pd2_png};
const lv_img_dsc_t * ui_imgset_pe[2] = {&ui_img_sg_pe1_png, &ui_img_sg_pe2_png};
const lv_img_dsc_t * ui_imgset_qc[2] = {&ui_img_sg_qc1_png, &ui_img_sg_qc2_png};
const lv_img_dsc_t * ui_imgset_res[2] = {&ui_img_sg_res1_png, &ui_img_sg_res2_png};
const lv_img_dsc_t * ui_imgset_rf[2] = {&ui_img_sg_rf1_png, &ui_img_sg_rf2_png};
const lv_img_dsc_t * ui_imgset_rg[2] = {&ui_img_sg_rg1_png, &ui_img_sg_rg2_png};
const lv_img_dsc_t * ui_imgset_rr[2] = {&ui_img_sg_rr1_png, &ui_img_sg_rr2_png};
const lv_img_dsc_t * ui_imgset_rs[2] = {&ui_img_sg_rs1_png, &ui_img_sg_rs2_png};
const lv_img_dsc_t * ui_imgset_seaf[2] = {&ui_img_sg_seaf1_png, &ui_img_sg_seaf2_png};
const lv_img_dsc_t * ui_imgset_sef[2] = {&ui_img_sg_sef1_png, &ui_img_sg_sef2_png};
const lv_img_dsc_t * ui_imgset_sgp[2] = {&ui_img_sg_sgp1_png, &ui_img_sg_sgp2_png};
const lv_img_dsc_t * ui_imgset_sgr[2] = {&ui_img_sg_sgr1_png, &ui_img_sg_sgr2_png};
const lv_img_dsc_t * ui_imgset_sos[2] = {&ui_img_sg_sos1_png, &ui_img_sg_sos2_png};
const lv_img_dsc_t * ui_imgset_sp[2] = {&ui_img_sg_sp1_png, &ui_img_sg_sp2_png};
const lv_img_dsc_t * ui_imgset_spr[2] = {&ui_img_sg_spr1_png, &ui_img_sg_spr2_png};
const lv_img_dsc_t * ui_imgset_ste[2] = {&ui_img_sg_ste1_png, &ui_img_sg_ste2_png};
const lv_img_dsc_t * ui_imgset_sup[2] = {&ui_img_sg_sup1_png, &ui_img_sg_sup2_png};
const lv_img_dsc_t * ui_imgset_sw[2] = {&ui_img_sg_sw1_png, &ui_img_sg_sw2_png};
const lv_img_dsc_t * ui_imgset_td[2] = {&ui_img_sg_td1_png, &ui_img_sg_td2_png};
const lv_img_dsc_t * ui_imgset_tt[2] = {&ui_img_sg_tt1_png, &ui_img_sg_tt2_png};
const lv_img_dsc_t * ui_imgset_ud[2] = {&ui_img_sg_ud1_png, &ui_img_sg_ud2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SplashFade_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_) / (sizeof(lv_img_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Intro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 1000, 2000, &ui_Setup_screen_init);
        SplashFade_Animation(ui_Splash, 0);
    }
}

void ui_event_Setup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        assignStratagems(e);
    }
}

void ui_event_WeaponsMG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsHMG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsSW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsAC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsAMR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsARL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsEAT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsGL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsRG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsRR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsSPR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsQC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsLC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsAT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsFT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_WeaponsSTE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksBSB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksSGP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksGD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksGDB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksGDR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksSUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksJP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksPE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BackpacksEE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryMGS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryGS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryACS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryHMGE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationarySGR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryMS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryRS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryEMS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryAPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryATM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StationaryIM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Strikes120(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Strikes380(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesORS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOGB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOAS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOPS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOWB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOES(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesONB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOGS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_StrikesOSS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Eagle110(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_Eagle500(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_EagleA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_EagleCB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_EagleSR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_EagleNA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_EagleSS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        deselectStratagem(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        selectStratagem(e);
    }
}

void ui_event_BtnConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Config, LV_SCR_LOAD_ANIM_MOVE_TOP, 1000, 0, &ui_Config_screen_init);
    }
}

void ui_event_BtnReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetStratagems(e);
    }
}

void ui_event_BtnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        GotoGame(e);
    }
}

void ui_event_BtnReinforce(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem1(e);
    }
}

void ui_event_BtnResupply(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem2(e);
    }
}

void ui_event_BtnSOS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem3(e);
    }
}

void ui_event_BtnRearm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem4(e);
    }
}

void ui_event_CustomStratagem1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem5(e);
    }
}

void ui_event_CustomStratagem2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem6(e);
    }
}

void ui_event_CustomStratagem3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem7(e);
    }
}

void ui_event_CustomStratagem4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        triggerStratagem8(e);
    }
}

void ui_event_BtnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 0, &ui_Setup_screen_init);
    }
}

void ui_event_SldBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeBrightness(e);
    }
}

void ui_event_ChbFlip(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FlipScreen(e);
    }
}

void ui_event_ChbMute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MuteSound(e);
    }
}

void ui_event_SldDelay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeDelay(e);
    }
}

void ui_event_BtnTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        KeyboardDemo(e);
    }
}

void ui_event_SetupFooter2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 1000, 0, &ui_Setup_screen_init);
    }
}

void ui_event_BtnSetup(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 1000, 0, &ui_Setup_screen_init);
    }
}

void ui_event_BtnDefault(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ResetConfig(e);
    }
}

void ui_event_BtnReboot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        RebootDevice(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Intro_screen_init();
    ui_Setup_screen_init();
    ui_Game_screen_init();
    ui_Config_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Intro);
}
