// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void SplashFade_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Intro
void ui_Intro_screen_init(void);
void ui_event_Intro(lv_event_t * e);
extern lv_obj_t * ui_Intro;
extern lv_obj_t * ui_Splash;
// CUSTOM VARIABLES

// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
void ui_event_Setup(lv_event_t * e);
extern lv_obj_t * ui_Setup;
extern lv_obj_t * ui_TabStratagems;
extern lv_obj_t * ui_Weapon;
extern lv_obj_t * ui_Container2;
void ui_event_WeaponsMG(lv_event_t * e);
extern lv_obj_t * ui_WeaponsMG;
void ui_event_WeaponsHMG(lv_event_t * e);
extern lv_obj_t * ui_WeaponsHMG;
void ui_event_WeaponsSW(lv_event_t * e);
extern lv_obj_t * ui_WeaponsSW;
void ui_event_WeaponsAC(lv_event_t * e);
extern lv_obj_t * ui_WeaponsAC;
void ui_event_WeaponsAMR(lv_event_t * e);
extern lv_obj_t * ui_WeaponsAMR;
void ui_event_WeaponsARL(lv_event_t * e);
extern lv_obj_t * ui_WeaponsARL;
void ui_event_WeaponsC(lv_event_t * e);
extern lv_obj_t * ui_WeaponsC;
void ui_event_WeaponsEAT(lv_event_t * e);
extern lv_obj_t * ui_WeaponsEAT;
void ui_event_WeaponsGL(lv_event_t * e);
extern lv_obj_t * ui_WeaponsGL;
void ui_event_WeaponsRG(lv_event_t * e);
extern lv_obj_t * ui_WeaponsRG;
void ui_event_WeaponsRR(lv_event_t * e);
extern lv_obj_t * ui_WeaponsRR;
void ui_event_WeaponsSPR(lv_event_t * e);
extern lv_obj_t * ui_WeaponsSPR;
void ui_event_WeaponsQC(lv_event_t * e);
extern lv_obj_t * ui_WeaponsQC;
void ui_event_WeaponsLC(lv_event_t * e);
extern lv_obj_t * ui_WeaponsLC;
void ui_event_WeaponsAT(lv_event_t * e);
extern lv_obj_t * ui_WeaponsAT;
void ui_event_WeaponsFT(lv_event_t * e);
extern lv_obj_t * ui_WeaponsFT;
void ui_event_WeaponsSTE(lv_event_t * e);
extern lv_obj_t * ui_WeaponsSTE;
extern lv_obj_t * ui_Backpack;
extern lv_obj_t * ui_Container1;
void ui_event_BackpacksBSB(lv_event_t * e);
extern lv_obj_t * ui_BackpacksBSB;
void ui_event_BackpacksSGP(lv_event_t * e);
extern lv_obj_t * ui_BackpacksSGP;
void ui_event_BackpacksGD(lv_event_t * e);
extern lv_obj_t * ui_BackpacksGD;
void ui_event_BackpacksGDB(lv_event_t * e);
extern lv_obj_t * ui_BackpacksGDB;
void ui_event_BackpacksGDR(lv_event_t * e);
extern lv_obj_t * ui_BackpacksGDR;
void ui_event_BackpacksSUP(lv_event_t * e);
extern lv_obj_t * ui_BackpacksSUP;
void ui_event_BackpacksJP(lv_event_t * e);
extern lv_obj_t * ui_BackpacksJP;
void ui_event_BackpacksPE(lv_event_t * e);
extern lv_obj_t * ui_BackpacksPE;
void ui_event_BackpacksEE(lv_event_t * e);
extern lv_obj_t * ui_BackpacksEE;
extern lv_obj_t * ui_Stationary;
extern lv_obj_t * ui_Container3;
void ui_event_StationaryMGS(lv_event_t * e);
extern lv_obj_t * ui_StationaryMGS;
void ui_event_StationaryGS(lv_event_t * e);
extern lv_obj_t * ui_StationaryGS;
void ui_event_StationaryACS(lv_event_t * e);
extern lv_obj_t * ui_StationaryACS;
void ui_event_StationaryHMGE(lv_event_t * e);
extern lv_obj_t * ui_StationaryHMGE;
void ui_event_StationaryTT(lv_event_t * e);
extern lv_obj_t * ui_StationaryTT;
void ui_event_StationarySGR(lv_event_t * e);
extern lv_obj_t * ui_StationarySGR;
void ui_event_StationaryMS(lv_event_t * e);
extern lv_obj_t * ui_StationaryMS;
void ui_event_StationaryRS(lv_event_t * e);
extern lv_obj_t * ui_StationaryRS;
void ui_event_StationaryEMS(lv_event_t * e);
extern lv_obj_t * ui_StationaryEMS;
void ui_event_StationaryAPM(lv_event_t * e);
extern lv_obj_t * ui_StationaryAPM;
void ui_event_StationaryATM(lv_event_t * e);
extern lv_obj_t * ui_StationaryATM;
void ui_event_StationaryIM(lv_event_t * e);
extern lv_obj_t * ui_StationaryIM;
extern lv_obj_t * ui_Strike;
extern lv_obj_t * ui_Container4;
void ui_event_Strikes120(lv_event_t * e);
extern lv_obj_t * ui_Strikes120;
void ui_event_Strikes380(lv_event_t * e);
extern lv_obj_t * ui_Strikes380;
void ui_event_StrikesORS(lv_event_t * e);
extern lv_obj_t * ui_StrikesORS;
void ui_event_StrikesOGB(lv_event_t * e);
extern lv_obj_t * ui_StrikesOGB;
void ui_event_StrikesOAS(lv_event_t * e);
extern lv_obj_t * ui_StrikesOAS;
void ui_event_StrikesOL(lv_event_t * e);
extern lv_obj_t * ui_StrikesOL;
void ui_event_StrikesOPS(lv_event_t * e);
extern lv_obj_t * ui_StrikesOPS;
void ui_event_StrikesOWB(lv_event_t * e);
extern lv_obj_t * ui_StrikesOWB;
void ui_event_StrikesOES(lv_event_t * e);
extern lv_obj_t * ui_StrikesOES;
void ui_event_StrikesONB(lv_event_t * e);
extern lv_obj_t * ui_StrikesONB;
void ui_event_StrikesOGS(lv_event_t * e);
extern lv_obj_t * ui_StrikesOGS;
void ui_event_StrikesOSS(lv_event_t * e);
extern lv_obj_t * ui_StrikesOSS;
extern lv_obj_t * ui_Eagle;
extern lv_obj_t * ui_Container7;
void ui_event_Eagle110(lv_event_t * e);
extern lv_obj_t * ui_Eagle110;
void ui_event_Eagle500(lv_event_t * e);
extern lv_obj_t * ui_Eagle500;
void ui_event_EagleA(lv_event_t * e);
extern lv_obj_t * ui_EagleA;
void ui_event_EagleCB(lv_event_t * e);
extern lv_obj_t * ui_EagleCB;
void ui_event_EagleSR(lv_event_t * e);
extern lv_obj_t * ui_EagleSR;
void ui_event_EagleNA(lv_event_t * e);
extern lv_obj_t * ui_EagleNA;
void ui_event_EagleSS(lv_event_t * e);
extern lv_obj_t * ui_EagleSS;
extern lv_obj_t * ui_SetupFooter;
void ui_event_BtnConfig(lv_event_t * e);
extern lv_obj_t * ui_BtnConfig;
extern lv_obj_t * ui_LblConfig;
void ui_event_BtnReset(lv_event_t * e);
extern lv_obj_t * ui_BtnReset;
extern lv_obj_t * ui_LblReset;
extern lv_obj_t * ui_BarAmount;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_LblCurAmount;
extern lv_obj_t * ui_LblMaxAmount;
void ui_event_BtnPlay(lv_event_t * e);
extern lv_obj_t * ui_BtnPlay;
extern lv_obj_t * ui_LblPlay;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BarAmount;
extern lv_obj_t * uic_LabelAmount;

// SCREEN: ui_Game
void ui_Game_screen_init(void);
extern lv_obj_t * ui_Game;
extern lv_obj_t * ui_BoxStratagems;
void ui_event_BtnReinforce(lv_event_t * e);
extern lv_obj_t * ui_BtnReinforce;
void ui_event_BtnResupply(lv_event_t * e);
extern lv_obj_t * ui_BtnResupply;
void ui_event_BtnSOS(lv_event_t * e);
extern lv_obj_t * ui_BtnSOS;
void ui_event_BtnRearm(lv_event_t * e);
extern lv_obj_t * ui_BtnRearm;
void ui_event_CustomStratagem1(lv_event_t * e);
extern lv_obj_t * ui_CustomStratagem1;
void ui_event_CustomStratagem2(lv_event_t * e);
extern lv_obj_t * ui_CustomStratagem2;
void ui_event_CustomStratagem3(lv_event_t * e);
extern lv_obj_t * ui_CustomStratagem3;
void ui_event_CustomStratagem4(lv_event_t * e);
extern lv_obj_t * ui_CustomStratagem4;
extern lv_obj_t * ui_GameFooter;
void ui_event_BtnBack(lv_event_t * e);
extern lv_obj_t * ui_BtnBack;
extern lv_obj_t * ui_LblBack;
// CUSTOM VARIABLES

// SCREEN: ui_Config
void ui_Config_screen_init(void);
extern lv_obj_t * ui_Config;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_LblDelay;
extern lv_obj_t * ui_LblDelay1;
void ui_event_SldDelay(lv_event_t * e);
extern lv_obj_t * ui_SldDelay;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LblBrightness;
extern lv_obj_t * ui_LblBrightness1;
void ui_event_SldBrightness(lv_event_t * e);
extern lv_obj_t * ui_SldBrightness;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label1;
void ui_event_ChbMute(lv_event_t * e);
extern lv_obj_t * ui_ChbMute;
extern lv_obj_t * ui_Label4;
void ui_event_SetupFooter2(lv_event_t * e);
extern lv_obj_t * ui_SetupFooter2;
void ui_event_BtnSetup(lv_event_t * e);
extern lv_obj_t * ui_BtnSetup;
extern lv_obj_t * ui_LblSetup;
extern lv_obj_t * ui_Container11;
void ui_event_BtnDemo(lv_event_t * e);
extern lv_obj_t * ui_BtnDemo;
extern lv_obj_t * ui_LblDemo;
void ui_event_BtnDefault(lv_event_t * e);
extern lv_obj_t * ui_BtnDefault;
extern lv_obj_t * ui_LblDefault;
void ui_event_BtnReboot(lv_event_t * e);
extern lv_obj_t * ui_BtnReboot;
extern lv_obj_t * ui_LblReboot;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ChbMute;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_intro_png);    // assets/intro.png
LV_IMG_DECLARE(ui_img_sg_mg1_png);    // assets/sg/MG1.png
LV_IMG_DECLARE(ui_img_sg_hmg1_png);    // assets/sg/HMG1.png
LV_IMG_DECLARE(ui_img_sg_sw1_png);    // assets/sg/SW1.png
LV_IMG_DECLARE(ui_img_sg_ac1_png);    // assets/sg/AC1.png
LV_IMG_DECLARE(ui_img_sg_amr1_png);    // assets/sg/AMR1.png
LV_IMG_DECLARE(ui_img_sg_arl1_png);    // assets/sg/ARL1.png
LV_IMG_DECLARE(ui_img_sg_c1_png);    // assets/sg/C1.png
LV_IMG_DECLARE(ui_img_sg_eat1_png);    // assets/sg/EAT1.png
LV_IMG_DECLARE(ui_img_sg_gl1_png);    // assets/sg/GL1.png
LV_IMG_DECLARE(ui_img_sg_rg1_png);    // assets/sg/RG1.png
LV_IMG_DECLARE(ui_img_sg_rr1_png);    // assets/sg/RR1.png
LV_IMG_DECLARE(ui_img_sg_spr1_png);    // assets/sg/SPR1.png
LV_IMG_DECLARE(ui_img_sg_qc1_png);    // assets/sg/QC1.png
LV_IMG_DECLARE(ui_img_sg_lc1_png);    // assets/sg/LC1.png
LV_IMG_DECLARE(ui_img_sg_at1_png);    // assets/sg/AT1.png
LV_IMG_DECLARE(ui_img_sg_ft1_png);    // assets/sg/FT1.png
LV_IMG_DECLARE(ui_img_sg_ste1_png);    // assets/sg/STE1.png
LV_IMG_DECLARE(ui_img_sg_bsb1_png);    // assets/sg/BSB1.png
LV_IMG_DECLARE(ui_img_sg_sgp1_png);    // assets/sg/SGP1.png
LV_IMG_DECLARE(ui_img_sg_gd1_png);    // assets/sg/GD1.png
LV_IMG_DECLARE(ui_img_sg_gdb1_png);    // assets/sg/GDB1.png
LV_IMG_DECLARE(ui_img_sg_gdr1_png);    // assets/sg/GDR1.png
LV_IMG_DECLARE(ui_img_sg_sup1_png);    // assets/sg/SUP1.png
LV_IMG_DECLARE(ui_img_sg_jp1_png);    // assets/sg/JP1.png
LV_IMG_DECLARE(ui_img_sg_pe1_png);    // assets/sg/PE1.png
LV_IMG_DECLARE(ui_img_sg_ee1_png);    // assets/sg/EE1.png
LV_IMG_DECLARE(ui_img_sg_mgs1_png);    // assets/sg/MGS1.png
LV_IMG_DECLARE(ui_img_sg_gs1_png);    // assets/sg/GS1.png
LV_IMG_DECLARE(ui_img_sg_acs1_png);    // assets/sg/ACS1.png
LV_IMG_DECLARE(ui_img_sg_hmge1_png);    // assets/sg/HMGE1.png
LV_IMG_DECLARE(ui_img_sg_tt1_png);    // assets/sg/TT1.png
LV_IMG_DECLARE(ui_img_sg_sgr1_png);    // assets/sg/SGR1.png
LV_IMG_DECLARE(ui_img_sg_ms1_png);    // assets/sg/MS1.png
LV_IMG_DECLARE(ui_img_sg_rs1_png);    // assets/sg/RS1.png
LV_IMG_DECLARE(ui_img_sg_ems1_png);    // assets/sg/EMS1.png
LV_IMG_DECLARE(ui_img_sg_apm1_png);    // assets/sg/APM1.png
LV_IMG_DECLARE(ui_img_sg_atm1_png);    // assets/sg/ATM1.png
LV_IMG_DECLARE(ui_img_sg_im1_png);    // assets/sg/IM1.png
LV_IMG_DECLARE(ui_img_sg_1201_png);    // assets/sg/1201.png
LV_IMG_DECLARE(ui_img_sg_3801_png);    // assets/sg/3801.png
LV_IMG_DECLARE(ui_img_sg_ors1_png);    // assets/sg/ORS1.png
LV_IMG_DECLARE(ui_img_sg_ogb1_png);    // assets/sg/OGB1.png
LV_IMG_DECLARE(ui_img_sg_oas1_png);    // assets/sg/OAS1.png
LV_IMG_DECLARE(ui_img_sg_ol1_png);    // assets/sg/OL1.png
LV_IMG_DECLARE(ui_img_sg_ops1_png);    // assets/sg/OPS1.png
LV_IMG_DECLARE(ui_img_sg_owb1_png);    // assets/sg/OWB1.png
LV_IMG_DECLARE(ui_img_sg_oes1_png);    // assets/sg/OES1.png
LV_IMG_DECLARE(ui_img_sg_onb1_png);    // assets/sg/ONB1.png
LV_IMG_DECLARE(ui_img_sg_ogs1_png);    // assets/sg/OGS1.png
LV_IMG_DECLARE(ui_img_sg_oss1_png);    // assets/sg/OSS1.png
LV_IMG_DECLARE(ui_img_sg_e1101_png);    // assets/sg/E1101.png
LV_IMG_DECLARE(ui_img_sg_e5001_png);    // assets/sg/E5001.png
LV_IMG_DECLARE(ui_img_sg_ea1_png);    // assets/sg/EA1.png
LV_IMG_DECLARE(ui_img_sg_ecb1_png);    // assets/sg/ECB1.png
LV_IMG_DECLARE(ui_img_sg_esr1_png);    // assets/sg/ESR1.png
LV_IMG_DECLARE(ui_img_sg_ena1_png);    // assets/sg/ENA1.png
LV_IMG_DECLARE(ui_img_sg_ess1_png);    // assets/sg/ESS1.png
LV_IMG_DECLARE(ui_img_sg_rf1_png);    // assets/sg/RF1.png
LV_IMG_DECLARE(ui_img_sg_res1_png);    // assets/sg/RES1.png
LV_IMG_DECLARE(ui_img_sg_sos1_png);    // assets/sg/SOS1.png
LV_IMG_DECLARE(ui_img_sg_er1_png);    // assets/sg/ER1.png
LV_IMG_DECLARE(ui_img_sg_1202_png);    // assets/sg/1202.png
LV_IMG_DECLARE(ui_img_sg_3802_png);    // assets/sg/3802.png
LV_IMG_DECLARE(ui_img_sg_ac2_png);    // assets/sg/AC2.png
LV_IMG_DECLARE(ui_img_sg_acs2_png);    // assets/sg/ACS2.png
LV_IMG_DECLARE(ui_img_sg_amr2_png);    // assets/sg/AMR2.png
LV_IMG_DECLARE(ui_img_sg_apm2_png);    // assets/sg/APM2.png
LV_IMG_DECLARE(ui_img_sg_arl2_png);    // assets/sg/ARL2.png
LV_IMG_DECLARE(ui_img_sg_at2_png);    // assets/sg/AT2.png
LV_IMG_DECLARE(ui_img_sg_atm2_png);    // assets/sg/ATM2.png
LV_IMG_DECLARE(ui_img_sg_bsb2_png);    // assets/sg/BSB2.png
LV_IMG_DECLARE(ui_img_sg_c2_png);    // assets/sg/C2.png
LV_IMG_DECLARE(ui_img_sg_dfv1_png);    // assets/sg/DFV1.png
LV_IMG_DECLARE(ui_img_sg_dfv2_png);    // assets/sg/DFV2.png
LV_IMG_DECLARE(ui_img_sg_e1102_png);    // assets/sg/E1102.png
LV_IMG_DECLARE(ui_img_sg_e5002_png);    // assets/sg/E5002.png
LV_IMG_DECLARE(ui_img_sg_ea2_png);    // assets/sg/EA2.png
LV_IMG_DECLARE(ui_img_sg_eat2_png);    // assets/sg/EAT2.png
LV_IMG_DECLARE(ui_img_sg_ecb2_png);    // assets/sg/ECB2.png
LV_IMG_DECLARE(ui_img_sg_ee2_png);    // assets/sg/EE2.png
LV_IMG_DECLARE(ui_img_sg_ems2_png);    // assets/sg/EMS2.png
LV_IMG_DECLARE(ui_img_sg_ena2_png);    // assets/sg/ENA2.png
LV_IMG_DECLARE(ui_img_sg_er2_png);    // assets/sg/ER2.png
LV_IMG_DECLARE(ui_img_sg_esr2_png);    // assets/sg/ESR2.png
LV_IMG_DECLARE(ui_img_sg_ess2_png);    // assets/sg/ESS2.png
LV_IMG_DECLARE(ui_img_sg_ft2_png);    // assets/sg/FT2.png
LV_IMG_DECLARE(ui_img_sg_gd2_png);    // assets/sg/GD2.png
LV_IMG_DECLARE(ui_img_sg_gdb2_png);    // assets/sg/GDB2.png
LV_IMG_DECLARE(ui_img_sg_gdr2_png);    // assets/sg/GDR2.png
LV_IMG_DECLARE(ui_img_sg_gl2_png);    // assets/sg/GL2.png
LV_IMG_DECLARE(ui_img_sg_gs2_png);    // assets/sg/GS2.png
LV_IMG_DECLARE(ui_img_sg_hb1_png);    // assets/sg/HB1.png
LV_IMG_DECLARE(ui_img_sg_hb2_png);    // assets/sg/HB2.png
LV_IMG_DECLARE(ui_img_sg_hbd1_png);    // assets/sg/HBD1.png
LV_IMG_DECLARE(ui_img_sg_hbd2_png);    // assets/sg/HBD2.png
LV_IMG_DECLARE(ui_img_sg_hmg2_png);    // assets/sg/HMG2.png
LV_IMG_DECLARE(ui_img_sg_hmge2_png);    // assets/sg/HMGE2.png
LV_IMG_DECLARE(ui_img_sg_im2_png);    // assets/sg/IM2.png
LV_IMG_DECLARE(ui_img_sg_jp2_png);    // assets/sg/JP2.png
LV_IMG_DECLARE(ui_img_sg_lc2_png);    // assets/sg/LC2.png
LV_IMG_DECLARE(ui_img_sg_mg2_png);    // assets/sg/MG2.png
LV_IMG_DECLARE(ui_img_sg_mgs2_png);    // assets/sg/MGS2.png
LV_IMG_DECLARE(ui_img_sg_ms2_png);    // assets/sg/MS2.png
LV_IMG_DECLARE(ui_img_sg_oas2_png);    // assets/sg/OAS2.png
LV_IMG_DECLARE(ui_img_sg_oes2_png);    // assets/sg/OES2.png
LV_IMG_DECLARE(ui_img_sg_ogb2_png);    // assets/sg/OGB2.png
LV_IMG_DECLARE(ui_img_sg_ogs2_png);    // assets/sg/OGS2.png
LV_IMG_DECLARE(ui_img_sg_oif1_png);    // assets/sg/OIF1.png
LV_IMG_DECLARE(ui_img_sg_oif2_png);    // assets/sg/OIF2.png
LV_IMG_DECLARE(ui_img_sg_ol2_png);    // assets/sg/OL2.png
LV_IMG_DECLARE(ui_img_sg_onb2_png);    // assets/sg/ONB2.png
LV_IMG_DECLARE(ui_img_sg_ops2_png);    // assets/sg/OPS2.png
LV_IMG_DECLARE(ui_img_sg_ors2_png);    // assets/sg/ORS2.png
LV_IMG_DECLARE(ui_img_sg_oss2_png);    // assets/sg/OSS2.png
LV_IMG_DECLARE(ui_img_sg_owb2_png);    // assets/sg/OWB2.png
LV_IMG_DECLARE(ui_img_sg_pd1_png);    // assets/sg/PD1.png
LV_IMG_DECLARE(ui_img_sg_pd2_png);    // assets/sg/PD2.png
LV_IMG_DECLARE(ui_img_sg_pe2_png);    // assets/sg/PE2.png
LV_IMG_DECLARE(ui_img_sg_qc2_png);    // assets/sg/QC2.png
LV_IMG_DECLARE(ui_img_sg_res2_png);    // assets/sg/RES2.png
LV_IMG_DECLARE(ui_img_sg_rf2_png);    // assets/sg/RF2.png
LV_IMG_DECLARE(ui_img_sg_rg2_png);    // assets/sg/RG2.png
LV_IMG_DECLARE(ui_img_sg_rr2_png);    // assets/sg/RR2.png
LV_IMG_DECLARE(ui_img_sg_rs2_png);    // assets/sg/RS2.png
LV_IMG_DECLARE(ui_img_sg_seaf1_png);    // assets/sg/SEAF1.png
LV_IMG_DECLARE(ui_img_sg_seaf2_png);    // assets/sg/SEAF2.png
LV_IMG_DECLARE(ui_img_sg_sef1_png);    // assets/sg/SEF1.png
LV_IMG_DECLARE(ui_img_sg_sef2_png);    // assets/sg/SEF2.png
LV_IMG_DECLARE(ui_img_sg_sgp2_png);    // assets/sg/SGP2.png
LV_IMG_DECLARE(ui_img_sg_sgr2_png);    // assets/sg/SGR2.png
LV_IMG_DECLARE(ui_img_sg_sos2_png);    // assets/sg/SOS2.png
LV_IMG_DECLARE(ui_img_sg_sp1_png);    // assets/sg/SP1.png
LV_IMG_DECLARE(ui_img_sg_sp2_png);    // assets/sg/SP2.png
LV_IMG_DECLARE(ui_img_sg_spr2_png);    // assets/sg/SPR2.png
LV_IMG_DECLARE(ui_img_sg_ste2_png);    // assets/sg/STE2.png
LV_IMG_DECLARE(ui_img_sg_sup2_png);    // assets/sg/SUP2.png
LV_IMG_DECLARE(ui_img_sg_sw2_png);    // assets/sg/SW2.png
LV_IMG_DECLARE(ui_img_sg_td1_png);    // assets/sg/TD1.png
LV_IMG_DECLARE(ui_img_sg_td2_png);    // assets/sg/TD2.png
LV_IMG_DECLARE(ui_img_sg_tt2_png);    // assets/sg/TT2.png
LV_IMG_DECLARE(ui_img_sg_ud1_png);    // assets/sg/UD1.png
LV_IMG_DECLARE(ui_img_sg_ud2_png);    // assets/sg/UD2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
