// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "hid_dev.h"

uint8_t strategemsAmount = 0;
lv_obj_t *buttons[4];

void deselectStratagem(lv_event_t *e)
{
	if (strategemsAmount > 0)
	{
		strategemsAmount--;
	}

	for (uint8_t c = 0; c < 4; c++)
	{
		if (buttons[c] == e->target)
		{
			buttons[c] = NULL;
		}
	}

	updateStratagemSelection();
}

void selectStratagem(lv_event_t *e)
{
	for (uint8_t c = 0; c < 4; c++)
	{
		if (buttons[c] == NULL)
		{
			buttons[c] = e->target;

			break;
		}
	}

	strategemsAmount++;

	updateStratagemSelection();
}

void updateStratagemSelection()
{
	lv_bar_set_value(uic_Amount, strategemsAmount, LV_ANIM_OFF);

	char textAmount = (char)(strategemsAmount + '0');

	lv_label_set_text(ui_Label1, &textAmount);

	if (strategemsAmount == 4)
	{
		_ui_screen_change(&ui_Game, LV_SCR_LOAD_ANIM_MOVE_LEFT, 1000, 100, &ui_Game_screen_init);
	}
}

void resetStratagems(lv_event_t *e)
{
	strategemsAmount = 0;

	for (uint8_t c = 0; c < 4; c++)
	{
		lv_obj_clear_state(buttons[c], LV_STATE_CHECKED);

		buttons[c] = NULL;
	}

	updateStratagemSelection();

	_ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 0, &ui_Setup_screen_init);
}

void triggerStratagem1(lv_event_t * e)
{
	uint8_t sequence[8] = {HID_KEY_H,
						   HID_KEY_E,
						   HID_KEY_L,
						   HID_KEY_L,
						   HID_KEY_O,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem2(lv_event_t * e)
{
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem3(lv_event_t * e)
{
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem4(lv_event_t * e)
{
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}