// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

extern void assignStratagems(lv_event_t * e);
void deselectStratagem(lv_event_t * e);
void selectStratagem(lv_event_t * e);
void triggerStratagemStd1(lv_event_t * e);
void triggerStratagemStd2(lv_event_t * e);
void triggerStratagemStd3(lv_event_t * e);
void triggerStratagemStd4(lv_event_t * e);
void triggerStratagemUser1(lv_event_t * e);
void triggerStratagemUser2(lv_event_t * e);
void triggerStratagemUser3(lv_event_t * e);
void triggerStratagemUser4(lv_event_t * e);
void triggerStratagemUser5(lv_event_t * e);
void triggerStratagemUser6(lv_event_t * e);
void triggerStratagemStd5(lv_event_t * e);
void triggerStratagemStd6(lv_event_t * e);
void resetStratagems(lv_event_t * e);
void ChangeKeymap(lv_event_t * e);
void updateStratagemSelection();
void ChangeDelay(lv_event_t * e);
void ChangeBrightness(lv_event_t * e);
void MuteSound(lv_event_t * e);
void ResetConfig(lv_event_t * e);
void RebootDevice(lv_event_t * e);
void GotoGame(lv_event_t * e);
void KeyboardDemo(lv_event_t * e);
void FlipScreen(lv_event_t * e);
void TabChanged(lv_event_t * e);
void ChangeConnectivity(lv_event_t * e);
void _executeStdStratagem(uint8_t *sequence, char *path);
void _executeUserStratagem(uint8_t index);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
