// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "hid_dev.h"
#include "esp_log.h"

uint8_t strategemsAmount = 0;
lv_obj_t *buttons[4];
int indices[4] = {0, 0, 0, 0};

void deselectStratagem(lv_event_t *e)
{
	if (strategemsAmount > 0)
	{
		strategemsAmount--;
	}

	for (uint8_t c = 0; c < 4; c++)
	{
		if (buttons[c] == e->target)
		{
			buttons[c] = NULL;
		}
	}

	updateStratagemSelection();
}

void selectStratagem(lv_event_t *e)
{
	for (uint8_t c = 0; c < 4; c++)
	{
		if (buttons[c] == NULL)
		{
			buttons[c] = e->target;
			indices[c] = (int)lv_obj_get_user_data(e->target);
			break;
		}
	}

	strategemsAmount++;

	updateStratagemSelection();
}

void updateStratagemSelection()
{
	lv_bar_set_value(uic_BarAmount, strategemsAmount, LV_ANIM_OFF);

	char textAmount = (char)(strategemsAmount + '0');
	lv_label_set_text(ui_LabelAmount, &textAmount);

	if (strategemsAmount == 4)
	{
		for (uint8_t c = 0; c < 4; c++)
		{
			if (buttons[c] != NULL)
			{
				const lv_obj_t *button = buttons[c];
				const lv_img_dsc_t *bgImg = lv_obj_get_style_bg_img_src(button, LV_PART_MAIN | LV_STATE_DEFAULT);

				switch (c)
				{
				case 0:
					lv_obj_set_style_bg_img_src(ui_CustomStratagem1, bgImg, LV_PART_MAIN | LV_STATE_DEFAULT);
					break;
				case 1:
					lv_obj_set_style_bg_img_src(ui_CustomStratagem2, bgImg, LV_PART_MAIN | LV_STATE_DEFAULT);
					break;
				case 2:
					lv_obj_set_style_bg_img_src(ui_CustomStratagem3, bgImg, LV_PART_MAIN | LV_STATE_DEFAULT);
					break;
				case 3:
					lv_obj_set_style_bg_img_src(ui_CustomStratagem4, bgImg, LV_PART_MAIN | LV_STATE_DEFAULT);
					break;
				}
			}
		}

		_ui_screen_change(&ui_Game, LV_SCR_LOAD_ANIM_MOVE_LEFT, 1000, 100, &ui_Game_screen_init);
	}
}

void resetStratagems(lv_event_t *e)
{
	strategemsAmount = 0;

	for (uint8_t c = 0; c < 4; c++)
	{
		if (buttons[c] != NULL)
		{
			lv_obj_clear_state(buttons[c], LV_STATE_CHECKED);
			buttons[c] = NULL;
			indices[c] = 0;
		}
	}

	updateStratagemSelection();
}

uint8_t sequences[71][8] = {
	// 0
	// MG-43 Machine Gun
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0,
	 0},

	// 1
	// APW-1 Anti-Materiel Rifle
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 0,
	 0,
	 0},

	// 2
	// M-105 Stalwart
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 0,
	 0},

	// 3
	// EAT-17 Expendable Anti-tank
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0,
	 0},

	// 4
	// MLS-4X Commando
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0,
	 0},

	// 5
	// GR-8 Recoilless Rifle
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 HID_KEY_LEFT_ARROW,
	 0,
	 0,
	 0},

	// 6
	// FLAM-40 Flamethrower
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 0,
	 0,
	 0},

	// 7
	// AC-8 Autocannon
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0},

	// 8
	// MG-206 Heavy Machine Gun
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_DOWN_ARROW,
	 0,
	 0,
	 0},

	// 9
	// RS-422 Railgun
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0},

	// 10
	// FAF-14 Spear Launcher
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_DOWN_ARROW,
	 0,
	 0,
	 0},

	// 11
	// GL-21 Grenade Launcher
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 0,
	 0,
	 0},

	// 12
	// LAS-98 Laser Cannon
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 0,
	 0,
	 0},

	// 13
	// ARC-3 Arc Thrower
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_LEFT_ARROW,
	 0,
	 0},

	// 14
	// LAS-99 Quasar Cannon
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0,
	 0},

	// 15
	// RL-77 Airburst Rocket Launcher
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_RIGHT_ARROW,
	 0,
	 0,
	 0},

	// 16
	// TX-41 Sterilizer
	{HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 HID_KEY_UP_ARROW,
	 HID_KEY_DOWN_ARROW,
	 HID_KEY_LEFT_ARROW,
	 0,
	 0,
	 0}

	//
};

void assignStratagems(lv_event_t * e)
{
	ui_WeaponsAC->user_data = 7;
	ui_WeaponsAMR->user_data = 1;
	ui_WeaponsARL->user_data = 15;
	ui_WeaponsAT->user_data = 13;
}


void triggerStratagem1(lv_event_t *e)
{
	// Reinforce
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem2(lv_event_t *e)
{
	// Resupply
	uint8_t sequence[8] = {HID_KEY_DOWN_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_UP_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   0,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem3(lv_event_t *e)
{
	// SOS
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_DOWN_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem4(lv_event_t *e)
{
	// Eagle rearm
	uint8_t sequence[8] = {HID_KEY_UP_ARROW,
						   HID_KEY_UP_ARROW,
						   HID_KEY_LEFT_ARROW,
						   HID_KEY_UP_ARROW,
						   HID_KEY_RIGHT_ARROW,
						   0,
						   0,
						   0};

	setStratagemCode(sequence);
}

void triggerStratagem5(lv_event_t *e)
{
	uint8_t index = indices[0];

	setStratagemCode(sequences[index]);
}

void triggerStratagem6(lv_event_t *e)
{
	uint8_t index = indices[1];

	setStratagemCode(sequences[index]);
}

void triggerStratagem7(lv_event_t *e)
{
	uint8_t index = indices[2];

	setStratagemCode(sequences[index]);
}

void triggerStratagem8(lv_event_t *e)
{
	uint8_t index = indices[3];

	setStratagemCode(sequences[index]);
}