// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "hid_dev.h"
#include "esp_log.h"
#include "stratagems.h"
#include "i2s_player.h"
#include "main.h"
#include "configration.h"
#include "ui_assignment.h"

const char *TAG_EVT = "Events";

#define MAX_USER_STRATAGEMS 6

// User button list
lv_obj_t *buttons[MAX_USER_STRATAGEMS];
// Stratagem list index of user buttons
int indices[MAX_USER_STRATAGEMS];
// Stratagem list index of user buttons
int types[MAX_USER_STRATAGEMS];
// Amount of user assigned stratagems
uint8_t strategemsAmount = 0;

// HID input mask for special keys
#define INPUT_CTRL_MASK 1 // 1 CTRL left

// Unassign stratagem item from button
void deselectStratagem(lv_event_t *e)
{
	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		if (buttons[c] == e->target)
		{
			buttons[c] = NULL;
			indices[c] = -1;
			types[c] = -1;
		}
	}

	updateStratagemSelection();

	playbackSound(SND_DESELECT);
}

// Assign stratagem item from button
void selectStratagem(lv_event_t *e)
{
	if (strategemsAmount < MAX_USER_STRATAGEMS)
	{
		for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
		{
			if (buttons[c] == NULL)
			{
				enum stratagemType type = (enum stratagemType)lv_obj_get_user_data(e->target);
				int index = -1;

				for (int c = 0; c < sizeof(strategems); c++)
				{
					stratagem item = strategems[c];

					if (item.type == type)
					{
						index = c;
						break;
					}
				}

				buttons[c] = e->target;
				indices[c] = index;
				types[c] = type;
				break;
			}
		}

		updateStratagemSelection();

		playbackSound(SND_SELECT);
	}
	else
	{
		lv_obj_clear_state(e->target, LV_STATE_CHECKED);

		playbackSound(SND_DESELECT);
	}
}

// Update selection in UI (text and bar)
void updateStratagemSelection()
{
	strategemsAmount = 0;

	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS - 1; c++)
	{
		if (buttons[c] == NULL)
		{
			buttons[c] = buttons[c + 1];
			indices[c] = indices[c + 1];
			types[c] = types[c + 1];

			buttons[c + 1] = NULL;
			indices[c + 1] = -1;
			types[c + 1] = -1;
		}
	}

	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		if (buttons[c] != NULL)
		{
			strategemsAmount++;
		}
	}

	lv_bar_set_value(uic_BarAmount, strategemsAmount, LV_ANIM_OFF);

	ui_theme_variable_t barColor = _ui_theme_color_colorTheme[0];

	if (strategemsAmount > 0 && strategemsAmount < 4)
	{
		barColor = _ui_theme_color_sgRed[0];
	}
	else if (strategemsAmount == 4)
	{
		barColor = _ui_theme_color_sgGreen[0];
	}
	else if (strategemsAmount > 4)
	{
		barColor = _ui_theme_color_sgBlue[0];
	}

	ui_object_set_themeable_style_property(uic_BarAmount, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, &barColor);
	ui_object_set_themeable_style_property(uic_BarAmount, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, &barColor);

	char textAmount[] = "0 / 0";
	textAmount[0] = (char)(strategemsAmount + '0');
	textAmount[4] = (char)(MAX_USER_STRATAGEMS + '0');

	lv_label_set_text(uic_LabelAmount, (void *)textAmount);

	if (strategemsAmount == MAX_USER_STRATAGEMS)
	{
		GotoGame(NULL);
	}
}

// Reset all selected stratagems from user
void resetStratagems(lv_event_t *e)
{
	if (strategemsAmount == 0)
	{
		return;
	}

	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		if (buttons[c] != NULL)
		{
			lv_obj_clear_state(buttons[c], LV_STATE_CHECKED);
			buttons[c] = NULL;
			indices[c] = -1;
			types[c] = -1;
		}
	}

	updateStratagemSelection();

	playbackSound(SND_RESET);
}

// Change connectivity (Bluetooth/USB)
void ChangeConnectivity(lv_event_t *e)
{
	uint8_t connectionType = lv_dropdown_get_selected(ui_DdConnectivity);

	setConnectivity(connectionType + 1, false);
}

// Change assigned keymap
void ChangeKeymap(lv_event_t *e)
{
	uint8_t keymapIndex = lv_dropdown_get_selected(ui_DdKeymap);

	setKeymap(keymapIndex, false);
}

// Trigger 1st standard stratagem
void triggerStratagemStd(lv_event_t *e)
{
	if (e->target == ui_BtnReinforce)
	{
		uint8_t sequence[8] = {INPUT_UP,
							   INPUT_DOWN,
							   INPUT_RIGHT,
							   INPUT_LEFT,
							   INPUT_UP,
							   0,
							   0,
							   0};

		_executeStdStratagem(sequence,
							 SND_REINFORCE);
	}
	else if (e->target == ui_BtnResupply)
	{
		uint8_t sequence[8] = {INPUT_DOWN,
							   INPUT_DOWN,
							   INPUT_UP,
							   INPUT_RIGHT,
							   0,
							   0,
							   0,
							   0};

		_executeStdStratagem(sequence, SND_SUPPLY);
	}
	else if (e->target == ui_BtnSOS)
	{
		uint8_t sequence[8] = {INPUT_UP,
							   INPUT_DOWN,
							   INPUT_RIGHT,
							   INPUT_UP,
							   0,
							   0,
							   0,
							   0};

		_executeStdStratagem(sequence, SND_SOS);
	}
	else if (e->target == ui_BtnRearm)
	{
		uint8_t sequence[8] = {INPUT_UP,
							   INPUT_UP,
							   INPUT_LEFT,
							   INPUT_UP,
							   INPUT_RIGHT,
							   0,
							   0,
							   0};

		_executeStdStratagem(sequence, SND_EAGLE_RELOAD);
	}
	else if (e->target == ui_BtnHellbomb)
	{
		uint8_t sequence[8] = {INPUT_DOWN,
							   INPUT_UP,
							   INPUT_LEFT,
							   INPUT_DOWN,
							   INPUT_UP,
							   INPUT_RIGHT,
							   INPUT_DOWN,
							   INPUT_UP};

		_executeStdStratagem(sequence, NULL);
	}
	else if (e->target == ui_BtnSEAF)
	{
		uint8_t sequence[8] = {INPUT_RIGHT,
							   INPUT_UP,
							   INPUT_UP,
							   INPUT_DOWN,
							   0,
							   0,
							   0,
							   0};

		_executeStdStratagem(sequence, NULL);
	}
	else if (e->target == ui_BtnResupply)
	{
	}
	else if (e->target == ui_BtnResupply)
	{
	}
	else if (e->target == ui_BtnResupply)
	{
	}
	else if (e->target == ui_BtnResupply)
	{
	}
}

void _executeStdStratagem(uint8_t *sequence, char *path)
{
	setStratagemCode(sequence, INPUT_CTRL_MASK, false);

	if (path != NULL)
	{
		playbackSound(path);
	}
}

void _executeUserStratagem(uint8_t index)
{
	uint8_t itemIndex = indices[index];
	stratagem item = strategems[itemIndex];

	setStratagemCode(item.sequence, INPUT_CTRL_MASK, false);

	char *path = item.soundPath;

	playbackSound(path);
}

// Trigger 1st user stratagem
void triggerStratagemUser(lv_event_t *e)
{
	int8_t index = -1;

	if (e->target == ui_CustomStratagem1)
	{
		index = 0;
	}
	else if (e->target == ui_CustomStratagem2)
	{
		index = 1;
	}
	else if (e->target == ui_CustomStratagem3)
	{
		index = 2;
	}
	else if (e->target == ui_CustomStratagem4)
	{
		index = 3;
	}
	else if (e->target == ui_CustomStratagem5)
	{
		index = 4;
	}
	else if (e->target == ui_CustomStratagem6)
	{
		index = 5;
	}

	if (index >= 0)
	{
		_executeUserStratagem(index);
	}
}

// Change HID input delay
void ChangeDelay(lv_event_t *e)
{
	int32_t delay = lv_slider_get_value(e->target);

	setDelay(delay * 10, false);
}

// Change display brightness
void ChangeBrightness(lv_event_t *e)
{
	int32_t brightness = lv_slider_get_value(e->target);

	setBrightness(brightness * 10, false);
}

// Change sound mute (on/off)
void MuteSound(lv_event_t *e)
{
	bool muted = lv_obj_get_state(e->target) & LV_STATE_CHECKED ? true : false;

	setMuted(muted, false);
}

// Reset configuration to default
void ResetConfig(lv_event_t *e)
{
	resetConfig();
}

// Trigger keyboard demo (send "hello" via bluetooth connection to host)
void KeyboardDemo(lv_event_t *e)
{
	uint8_t sequence[8] = {HID_KEY_H,
						   HID_KEY_E,
						   HID_KEY_L,
						   HID_KEY_L,
						   HID_KEY_O,
						   0,
						   0,
						   0};

	setStratagemCode(sequence, 0, true);
}

// Trigger when tab navigation has changed
void TabChanged(lv_event_t *e)
{
	playbackSound(SND_SWIPE);
}

// Change screen orientation
void FlipScreen(lv_event_t *e)
{
	bool flip = lv_obj_get_state(e->target) & LV_STATE_CHECKED ? true : false;

	setRotation(flip ? LV_DISP_ROT_270 : LV_DISP_ROT_90, false);

	esp_restart();
}

// Goto game screen
void GotoGame(lv_event_t *e)
{
	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		const lv_obj_t *button = buttons[c];
		const lv_img_dsc_t *bgImg = lv_obj_get_style_bg_img_src(button, LV_PART_MAIN | LV_STATE_DEFAULT);
		const bool configured = buttons[c] != NULL;
		lv_obj_t *targetButton = ui_CustomStratagem1;

		bool useHiResIcon = true;

		switch (c)
		{
		case 1:
			targetButton = ui_CustomStratagem2;
			break;
		case 2:
			targetButton = ui_CustomStratagem3;
			break;
		case 3:
			targetButton = ui_CustomStratagem4;
			break;
		case 4:
			targetButton = ui_CustomStratagem5;
			useHiResIcon = false;
			break;
		case 5:
			targetButton = ui_CustomStratagem6;
			useHiResIcon = false;
			break;
		}

		uint8_t itemIndex = indices[c];
		stratagem item = strategems[itemIndex];
		const lv_img_dsc_t *hires = useHiResIcon ? item.imgHiRes : bgImg;

		if (configured)
		{
			ui_object_set_themeable_style_property(targetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
												   item.color);
			lv_obj_set_style_bg_img_src(targetButton, hires, LV_PART_MAIN | LV_STATE_DEFAULT);
			lv_obj_clear_flag(targetButton, LV_OBJ_FLAG_HIDDEN);
		}
		else
		{
			lv_obj_add_flag(targetButton, LV_OBJ_FLAG_HIDDEN);
		}
	}

	_ui_screen_change(&ui_Game, LV_SCR_LOAD_ANIM_MOVE_LEFT, 1000, 100, &ui_Game_screen_init);
}

char *presetKey(lv_obj_t *button, uint8_t itemIndex)
{
	static char key[3] = "p00";

	char presetIndex = '0';

	if (button == ui_BtnPreset1)
	{
		presetIndex = '1';
	}
	else if (button == ui_BtnPreset2)
	{
		presetIndex = '2';
	}

	char buffer[1];
	itoa(itemIndex, buffer, 10);

	key[1] = presetIndex;
	key[2] = buffer[0];

	return key;
}

void updatePresets()
{
	if (openConfig() != ESP_OK)
	{
		return;
	}

	bool hasPreset1 = getConfig("p10", -1) != -1;
	bool hasPreset2 = getConfig("p20", -1) != -1;

	closeConfig();

	ui_object_set_themeable_style_property(ui_BtnPreset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, hasPreset1 ? _ui_theme_color_sgGreen : _ui_theme_color_sgRed);
	ui_object_set_themeable_style_property(ui_BtnPreset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, hasPreset2 ? _ui_theme_color_sgGreen : _ui_theme_color_sgRed);
}

void GetPreset(lv_event_t *e)
{
	if (openConfig() != ESP_OK)
	{
		return;
	}

	resetStratagems(NULL);

	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		char *key = presetKey(e->target, c);

		int8_t presetIndex = getConfig(key, -1);
		types[c] = presetIndex;

		if (presetIndex == -1)
		{
			continue;
		}

		uint8_t listIndex = 0;
		uint16_t childIndex = 0;

		lv_obj_t *lists[8] = {
			ui_Rifle,
			ui_Special,
			ui_Backpack,
			ui_Supply,
			ui_Sentry,
			ui_Ground,
			ui_Strike,
			ui_Eagle};

		while (1)
		{
			lv_obj_t *child = lv_obj_get_child(lists[listIndex], childIndex);

			if (child == NULL)
			{
				if (listIndex < 6)
				{
					listIndex++;
					childIndex = 0;
					continue;
				}

				break;
			}

			enum stratagemType type = (enum stratagemType)lv_obj_get_user_data(child);

			if (type == presetIndex)
			{
				int index = -1;

				for (int c = 0; c < sizeof(strategems); c++)
				{
					stratagem item = strategems[c];

					if (item.type == type)
					{
						index = c;
						break;
					}
				}

				buttons[c] = child;
				indices[c] = index;

				lv_obj_add_state(child, LV_STATE_CHECKED);
				break;
			}

			childIndex++;
		}
	}

	closeConfig();

	updateStratagemSelection();
}

void SetPreset(lv_event_t *e)
{
	if (openConfig() != ESP_OK)
	{
		return;
	}

	for (uint8_t c = 0; c < MAX_USER_STRATAGEMS; c++)
	{
		char *key = presetKey(e->target, c);

		setConfig(key, types[c]);
	}

	closeConfig();

	updatePresets();

	playbackSound(SND_DESELECT);
}