// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_colorTheme[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_colorTheme[1] = {255};

const ui_theme_variable_t _ui_theme_color_colorActive[1] = {0xFFDF00};
const ui_theme_variable_t _ui_theme_alpha_colorActive[1] = {255};

const ui_theme_variable_t _ui_theme_color_sgGreen[1] = {0x679552};
const ui_theme_variable_t _ui_theme_alpha_sgGreen[1] = {255};

const ui_theme_variable_t _ui_theme_color_sgBlue[1] = {0x49ADC9};
const ui_theme_variable_t _ui_theme_alpha_sgBlue[1] = {255};

const ui_theme_variable_t _ui_theme_color_sgRed[1] = {0xDE7B6C};
const ui_theme_variable_t _ui_theme_alpha_sgRed[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

