// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_About_screen_init(void)
{
    ui_About = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_About, &ui_img_about_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_About, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorActive);
    ui_object_set_themeable_style_property(ui_About, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorActive);

    ui_LblVersion = lv_label_create(ui_About);
    lv_obj_set_width(ui_LblVersion, lv_pct(50));
    lv_obj_set_height(ui_LblVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblVersion, -8);
    lv_obj_set_y(ui_LblVersion, 8);
    lv_obj_set_align(ui_LblVersion, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LblVersion, "vX.X.X");
    ui_object_set_themeable_style_property(ui_LblVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_colorActive);
    ui_object_set_themeable_style_property(ui_LblVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_colorActive);
    lv_obj_set_style_text_align(ui_LblVersion, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblVersion, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_About, ui_event_About, LV_EVENT_ALL, NULL);

}
