name: PlatformIO CI

on:
  workflow_dispatch:
  
  #push:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run:  pio run -t mergebin
        env:  
          MERGED_BIN_PATH: hd2_macropad.bin

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.github_token }}
        
      - name: Upload archive to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.github_token }}
          file: .pio/build/LVGL-320-480/hd2_macropad.bin
          asset_name: hd2_macropad.bin
          tag: ${{ steps.tag_version.outputs.new_tag }}
          overwrite: true
          body: ${{ steps.tag_version.outputs.changelog }}
